export const STATIC_STRINGS = {
  DASHBOARD_TITLE: 'Super Admin Dashboard',
  DASHBOARD_LOGOUT: 'Logout',
  DASHBOARD_TOTAL_AGENCIES: 'Total Agencies',
  DASHBOARD_ALL_AGENCY_OWNERS: 'All Agency Owners',
  DASHBOARD_MANAGE_DESCRIPTION: 'Manage all agency owner accounts and their access.',
  DASHBOARD_CREATE_OWNER: 'Create Owner',
  DASHBOARD_NO_OWNERS: 'No owners found.',
  DASHBOARD_CONFIRM_DELETE: 'Are you sure you want to remove this owner?',
  DASHBOARD_OWNER_REMOVED: 'Owner removed',
  DASHBOARD_CREATE_OWNER_MODAL_TITLE: 'Create Owner Account',
  DASHBOARD_EDIT_OWNER_MODAL_TITLE: 'Edit Owner Account',
  
  TABLE_OWNER: 'Owner',
  TABLE_EMAIL: 'E-mail',
  TABLE_AGENCY: 'Agency',
  TABLE_JOINED: 'Joined',
  TABLE_ACTIONS: 'Actions',
  
  FORM_FULL_NAME: 'Full Name',
  FORM_AGENCY_NAME: 'Agency Name',
  FORM_EMAIL_ADDRESS: 'Email Address',
  FORM_CANCEL: 'Cancel',
  FORM_SAVE_CHANGES: 'Save Changes',
  FORM_CREATE_ACCOUNT: 'Create Account',
  FORM_SAVING: 'Saving...',
  FORM_CREATING: 'Creating...',
  FORM_NAME_REQUIRED: 'Name is required',
  FORM_AGENCY_REQUIRED: 'Agency is required',
  FORM_EMAIL_REQUIRED: 'Email is required',
  FORM_INVALID_FORMAT: 'Invalid format',
  FORM_ACCOUNT_UPDATED: 'Account updated',
  FORM_ACCOUNT_CREATED: 'Account created',
  FORM_SYSTEM_ERROR: 'System error',
  
  LOGIN_TITLE: 'Sign in',
  LOGIN_SUBTITLE: 'Super Admin Control Panel',
  LOGIN_EMAIL_LABEL: 'Email',
  LOGIN_PASSWORD_LABEL: 'Password',
  LOGIN_BUTTON: 'Login',
  LOGIN_VERIFYING: 'Verifying...',
  LOGIN_WELCOME_BACK: 'Welcome back',
  LOGIN_INVALID_CREDENTIALS: 'Invalid credentials',
  LOGIN_LOGIN_FAILED: 'Login failed',
  LOGIN_OTP_SENT: 'OTP sent successfully',
  LOGIN_OTP_VERIFIED: 'OTP Verified',
  LOGIN_INVALID_OTP: 'Invalid OTP',
  LOGIN_VERIFICATION_CODE: 'Verification Code',
  LOGIN_VERIFY_OTP_BUTTON: 'Verify OTP',
  LOGIN_RESEND_IN: 'Resend in',
  LOGIN_RESEND_OTP: 'Resend OTP',
  LOGIN_DIFFERENT_EMAIL: 'Use different email',
  LOGIN_LOGIN_WITH_OTP: 'Login with OTP',
  LOGIN_LOGIN_WITH_PASSWORD: 'Login with Password',
  LOGIN_PLATFORM_GOVERNANCE: 'Platform Governance',
  LOGIN_REDEFINED: 'redefined.',
  LOGIN_CONTROL_VAULT: 'Super Admin Control Vault',
  LOGIN_DESCRIPTION: 'The command center for AgencyFlow. Orchestrate roles, monitor system-wide performance, and manage high-level agency configurations.',
  LOGIN_TASKS_PROCESSED: 'Tasks Processed',
  LOGIN_UPTIME: 'Uptime',
};

export const SUPER_ADMIN_ACTIONS = {
  GET_OWNERS: 'get_owners',
  ADD_OWNER: 'add_owner',
  UPDATE_OWNER: 'update_owner',
  DELETE_OWNER: 'delete_owner',
} as const;

export const AUTH_ACTIONS = {
  LOGIN: 'login',
  REQUEST_OTP: 'request_otp',
  VERIFY_OTP: 'verify_otp',
} as const;

export const STORAGE_KEYS = {
  AUTH_TOKEN: 'auth_token',
  USER_DATA: 'user_data',
} as const;
