import { ROLES } from '@/constants/roles';
export { ROLES };

export const STATIC_STRINGS = {
  TITLE: 'AgencyFlow',
  // Task Management Defaults
  TASK_MGMT_ALL_ROLES: 'All Roles',
  TASK_MGMT_LABEL_DESCRIPTION: 'Description',
  TASK_MGMT_DEFAULT_CAMPAIGN: 'General',
  TASK_MGMT_DEFAULT_DELIVERY: 'General Delivery',
  TASK_MGMT_REQUIRED: 'Required',

  //Super Admin Dashboard
  DASHBOARD_TITLE: 'Super Admin Dashboard',
  DASHBOARD_LOGOUT: 'Logout',
  DASHBOARD_TOTAL_AGENCIES: 'Total Agencies',
  DASHBOARD_ALL_AGENCY_OWNERS: 'All Agency Owners',
  DASHBOARD_MANAGE_DESCRIPTION: 'Manage all agency owner accounts and their access.',
  DASHBOARD_CREATE_OWNER: 'Create Owner',
  DASHBOARD_NO_OWNERS: 'No owners found.',
  DASHBOARD_CONFIRM_DELETE: 'Are you sure you want to remove this owner?',
  DASHBOARD_OWNER_REMOVED: 'Owner removed',
  DASHBOARD_CREATE_OWNER_MODAL_TITLE: 'Create Owner Account',
  DASHBOARD_EDIT_OWNER_MODAL_TITLE: 'Edit Owner Account',

  // Table columns
  TABLE_OWNER: 'Owner',
  TABLE_EMAIL: 'E-mail',
  TABLE_AGENCY: 'Agency',
  TABLE_JOINED: 'Joined',
  TABLE_DATE: 'Date',
  TABLE_ACTIONS: 'Actions',
  TABLE_CLIENT: 'Client',
  TABLE_BRAND: 'Brand',
  TABLE_PACKAGE: 'Package',
  TABLE_PLAN: 'Plan',

  // Form labels / messages
  FORM_FULL_NAME: 'Full Name',
  FORM_AGENCY_NAME: 'Agency Name',
  FORM_EMAIL_ADDRESS: 'Email Address',
  FORM_CANCEL: 'Cancel',
  FORM_SAVE_CHANGES: 'Save Changes',
  FORM_CREATE_ACCOUNT: 'Create Account',
  FORM_SAVING: 'Saving...',
  FORM_CREATING: 'Creating...',
  FORM_NAME_REQUIRED: 'Name is required',
  FORM_AGENCY_REQUIRED: 'Agency is required',
  FORM_EMAIL_REQUIRED: 'Email is required',
  FORM_INVALID_FORMAT: 'Invalid format',
  FORM_ACCOUNT_UPDATED: 'Account updated',
  FORM_ACCOUNT_CREATED: 'Account created',
  FORM_SYSTEM_ERROR: 'System error',

  // Login page
  LOGIN_TITLE: 'Sign in',
  LOGIN_SUBTITLE: 'Super Admin Control Panel',
  LOGIN_EMAIL_LABEL: 'Email',
  LOGIN_PASSWORD_LABEL: 'Password',
  LOGIN_BUTTON: 'Login',
  LOGIN_VERIFYING: 'Verifying...',
  LOGIN_WELCOME_BACK: 'Welcome back',
  LOGIN_INVALID_CREDENTIALS: 'Invalid credentials',
  LOGIN_LOGIN_FAILED: 'Login failed',
  LOGIN_OTP_SENT: 'OTP sent successfully',
  LOGIN_OTP_VERIFIED: 'OTP Verified',
  LOGIN_INVALID_OTP: 'Invalid OTP',
  LOGIN_VERIFICATION_CODE: 'Verification Code',
  LOGIN_VERIFY_OTP_BUTTON: 'Verify OTP',
  LOGIN_RESEND_IN: 'Resend in',
  LOGIN_RESEND_OTP: 'Resend OTP',
  LOGIN_DIFFERENT_EMAIL: 'Use different email',
  LOGIN_LOGIN_WITH_OTP: 'Login with OTP',
  LOGIN_LOGIN_WITH_PASSWORD: 'Login with Password',
  LOGIN_PLATFORM_GOVERNANCE: 'Platform Governance',
  LOGIN_REDEFINED: 'redefined.',
  LOGIN_CONTROL_VAULT: 'Super Admin Control Vault',
  LOGIN_DESCRIPTION:
    'The command center for AgencyFlow. Orchestrate roles, monitor system-wide performance, and manage high-level agency configurations.',
  LOGIN_TASKS_PROCESSED: 'Tasks Processed',
  LOGIN_UPTIME: 'Uptime',

  // Ads Tracking page
  ADS_PAGE_TITLE: 'Ads Tracking',
  ADS_PAGE_SUBTITLE: 'Cross-platform ad performance across all campaigns',

  ADS_DATE_RANGE_7D: 'Last 7 days',
  ADS_DATE_RANGE_30D: 'Last 30 days',
  ADS_DATE_RANGE_90D: 'Last 90 days',

  ADS_KPI_TOTAL_SPEND: 'Total Spend',
  ADS_KPI_TOTAL_LEADS: 'Total Leads',
  ADS_KPI_TOTAL_CLICKS: 'Total Clicks',
  ADS_KPI_AVG_ROAS: 'Avg ROAS',

  ADS_KPI_SPEND_CHANGE: '+12%',
  ADS_KPI_LEADS_CHANGE: '+24%',
  ADS_KPI_CLICKS_CHANGE: '+18%',
  ADS_KPI_ROAS_CHANGE: '-0.3×',

  ADS_CHART_WEEKLY_TITLE: 'Weekly Spend vs Leads',
  ADS_CHART_PLATFORM_TITLE: 'Platform Breakdown',
  ADS_CHART_CLICK_TITLE: 'Click Trend',

  ADS_CHART_SERIES_SPEND: 'Spend (₹)',
  ADS_CHART_SERIES_LEADS: 'Leads',
  ADS_CHART_SERIES_CLICKS: 'Clicks',

  ADS_PLATFORM_SPEND_PCT_LABEL: '% of total spend',

  ADS_TABLE_SECTION_TITLE: 'Campaign Performance',
  ADS_TABLE_FILTER_ALL: 'All',
  ADS_TABLE_COL_CAMPAIGN: 'Campaign',
  ADS_TABLE_COL_PLATFORM: 'Platform',
  ADS_TABLE_COL_SPEND: 'Spend',
  ADS_TABLE_COL_LEADS: 'Leads',
  ADS_TABLE_COL_CLICKS: 'Clicks',
  ADS_TABLE_COL_ROAS: 'ROAS',
  ADS_TABLE_COL_STATUS: 'Status',

  ADS_MODAL_TITLE: 'Update Performance Data',
  ADS_MODAL_LABEL_SPEND: 'Add to Spend (₹)',
  ADS_MODAL_LABEL_LEADS: 'Add to Leads',
  ADS_MODAL_LABEL_CLICKS: 'Add to Clicks',
  ADS_MODAL_LABEL_ROAS: 'Average ROAS (×)',
  ADS_MODAL_PLACEHOLDER_ZERO: '0',
  ADS_MODAL_BTN_CANCEL: 'Cancel',
  ADS_MODAL_BTN_SUBMIT: 'Update Metrics',

  ADS_TOAST_METRICS_UPDATED: 'Ads performance data updated',

  ADS_STATUS_ACTIVE: 'active',
  ADS_STATUS_PAUSED: 'paused',
  ADS_STATUS_COMPLETED: 'completed',
  ADS_STATUS_DRAFT: 'draft',
  ADS_STATUS_ARCHIVED: 'archived',

  ADS_CHART_WEEK_1: 'Week 1',
  ADS_CHART_WEEK_2: 'Week 2',
  ADS_CHART_WEEK_3: 'Week 3',
  ADS_CHART_WEEK_4: 'Week 4',

  ADS_PLATFORM_META: 'Meta',
  ADS_PLATFORM_GOOGLE: 'Google',
  ADS_PLATFORM_INSTAGRAM: 'Instagram',
  ADS_PLATFORM_TIKTOK: 'TikTok',

  // Ads Reporting
  ADS_REPORT_TITLE: "Today's Performance Overview",
  ADS_REPORT_TOTAL_SPEND: 'Total Spend Today',
  ADS_REPORT_LEADS_GENERATED: 'Leads Generated',

  // Ads Dashboard
  ADS_DASHBOARD_TITLE: 'Ads Manager Dashboard',
  ADS_DASHBOARD_TEAM_NAME: 'Ads Team',
  ADS_DASHBOARD_ASSIGNED_TASKS: 'Assigned Tasks',
  ADS_DASHBOARD_STAT_PENDING_HANDOFF: 'Pending Handoff',
  ADS_DASHBOARD_STAT_ACTIVE_CAMPAIGNS: 'Active Campaigns',
  ADS_DASHBOARD_STAT_COMPLETED_ADS: 'Completed Ads',
  ADS_DASHBOARD_HISTORY_LOG: 'History Log:',
  ADS_DASHBOARD_FINALIZED_BY: 'Finalized by',
  ADS_DASHBOARD_TASK_FINALIZED: 'Task Finalized',
  ADS_DASHBOARD_NO_TASKS: 'No tasks found in',
  ADS_DASHBOARD_TASK_TAB_PENDING: 'Pending',
  ADS_DASHBOARD_TASK_TAB_IN_PROGRESS: 'In Progress',
  ADS_DASHBOARD_TASK_TAB_COMPLETED: 'Completed',
  ADS_DASHBOARD_OVERDUE: 'Overdue',
  ADS_DASHBOARD_NO_DEADLINE: 'No deadline',
  ADS_DASHBOARD_DAYS_LEFT: 'd left',
  ADS_DASHBOARD_TODAY: 'Today',

  // Campaign History Modal
  CAMPAIGN_HISTORY_MODAL_TITLE: 'Audit Log',
  CAMPAIGN_HISTORY_TRAIL: 'Audit Trail',
  CAMPAIGN_HISTORY_TOTAL_CHANGES: 'Total Changes',
  CAMPAIGN_HISTORY_NO_LOGS: 'No activity logs found for this campaign.',
  CAMPAIGN_HISTORY_UPDATED_FIELD: 'Updated field',
  CAMPAIGN_HISTORY_UPDATED_FIELDS: 'Updated fields',
  CAMPAIGN_HISTORY_EMPTY: 'Empty',
  CAMPAIGN_HISTORY_IMMUTABLE_NOTICE: 'Logs are immutable and reflect real-time activity.',
  CAMPAIGN_HISTORY_DONE: 'Done',
  CAMPAIGN_HISTORY_UPDATED_TEXT: 'Updated',

  // Campaign Management
  CAMPAIGN_MGMT_TITLE: 'Campaign Management',
  CAMPAIGN_MGMT_TOTAL: 'total',
  CAMPAIGN_MGMT_ACTIVE: 'active',
  CAMPAIGN_MGMT_EXPORT: 'Export',
  CAMPAIGN_MGMT_NEW: 'New Campaign',
  CAMPAIGN_MGMT_SEARCH_PLACEHOLDER: 'Search campaigns or clients…',
  CAMPAIGN_MGMT_ALL_STATUSES: 'All Statuses',
  CAMPAIGN_MGMT_ALL_CLIENTS: 'All Clients',
  CAMPAIGN_MGMT_ALL_STAGES: 'All Stages',
  CAMPAIGN_MGMT_NO_CAMPAIGNS: 'No campaigns found',
  CAMPAIGN_MGMT_NO_CAMPAIGNS_DESC: 'Try adjusting filters or create a new campaign.',
  CAMPAIGN_MGMT_DELETED_TOAST: 'campaigns deleted',
  CAMPAIGN_MGMT_PAUSED_TOAST: 'campaigns paused',
  CAMPAIGN_MGMT_STATUS_UPDATED: 'Campaign status updated',
  CAMPAIGN_MGMT_CREATED_TOAST: 'created',
  CAMPAIGN_MGMT_UPDATED_TOAST: 'Campaign updated',
  CAMPAIGN_MGMT_AUDIT_HISTORY: 'Audit History',
  CAMPAIGN_MGMT_EDIT: 'Edit',
  CAMPAIGN_MGMT_DELETE: 'Delete',
  CAMPAIGN_MGMT_LOG_PERFORMANCE: 'Log Performance',
  CAMPAIGN_MGMT_SELECTED: 'selected',
  CAMPAIGN_MGMT_BULK_PAUSE: 'Pause',
  CAMPAIGN_MGMT_BULK_DELETE: 'Delete',
  CAMPAIGN_MGMT_PAGINATION_SHOW: 'Show',
  CAMPAIGN_MGMT_PAGINATION_OF: 'of',
  CAMPAIGN_MGMT_PAGINATION_ENTRIES: 'entries',

  // Create Campaign Modal
  CREATE_CAMPAIGN_TITLE: 'Create New Campaign',
  CREATE_CAMPAIGN_SUBTITLE: 'Set up workflow automation and assign your team',
  CREATE_CAMPAIGN_STEP_DETAILS: 'Campaign Details',
  CREATE_CAMPAIGN_STEP_SETTINGS: 'Settings & Brief',
  CREATE_CAMPAIGN_PLATFORM: 'Ad Platform',
  CREATE_CAMPAIGN_OBJECTIVE: 'Objective',
  CREATE_CAMPAIGN_BUDGET: 'Daily Budget (INR)',
  CREATE_CAMPAIGN_LOCATION: 'Location',
  CREATE_CAMPAIGN_AUDIENCE: 'Target Audience',
  CREATE_CAMPAIGN_MEDIA_LOCATION: 'Photo/Video Location',
  CREATE_CAMPAIGN_AD_MANAGER: 'Ad Manager',
  CREATE_CAMPAIGN_DEADLINE: 'Deadline',
  CREATE_CAMPAIGN_NOTE: 'Note',
  CREATE_CAMPAIGN_PRIORITY: 'Priority Level',
  CREATE_CAMPAIGN_PRIORITY_DESC: 'Sets task urgency for your team.',
  CREATE_CAMPAIGN_CLIENT_DESC: 'Associate this campaign with a client.',
  CREATE_CAMPAIGN_NOTICE:
    'After creation, the Ad Manager will receive a notification and the workflow will begin.',
  CREATE_CAMPAIGN_LAUNCH: 'Launch Campaign ⚡',
  CREATE_CAMPAIGN_CREATING: 'Creating Campaign…',
  CREATE_CAMPAIGN_ERR_SELECT_OBJECTIVE: 'Select objective',
  CREATE_CAMPAIGN_ERR_BUDGET_REQUIRED: 'Daily budget is required',
  CREATE_CAMPAIGN_ERR_SELECT_MANAGER: 'Select an Ad Manager',
  CREATE_CAMPAIGN_ERR_SELECT_PLATFORM: 'Select at least one platform',
  CREATE_CAMPAIGN_SELECT_OBJECTIVE: 'Select objective…',
  CREATE_CAMPAIGN_SELECT_MANAGER: 'Select Ad Manager…',
  CREATE_CAMPAIGN_SELECT_CLIENT: 'Select client…',
  CREATE_CAMPAIGN_BACK: '← Back',
  CREATE_CAMPAIGN_CONTINUE: 'Continue →',
  CREATE_CAMPAIGN_STEP: 'Step',
  CREATE_CAMPAIGN_OF: 'of',

  // Campaign Fields
  CAMPAIGN_FIELD_NAME: 'Campaign Name',
  CAMPAIGN_FIELD_STATUS: 'Status',
  CAMPAIGN_FIELD_STAGE: 'Workflow Stage',
  CAMPAIGN_FIELD_BUDGET: 'Budget',
  CAMPAIGN_FIELD_DEADLINE: 'Deadline',
  CAMPAIGN_FIELD_ASSIGNEE: 'Assignee',
  CAMPAIGN_FIELD_PLATFORM: 'Platform',
  CAMPAIGN_FIELD_LEADS: 'Leads',
  CAMPAIGN_FIELD_ROAS: 'ROAS',
  CAMPAIGN_FIELD_SPEND: 'Spend',
  CAMPAIGN_FIELD_CLIENT: 'Client',

  // Delete Modal
  DELETE_MODAL_TITLE: 'Delete Campaign',
  DELETE_MODAL_CONFIRM: 'Are you sure you want to delete',
  DELETE_MODAL_DESC: 'This will permanently remove all associated tasks, files, and ad data.',
  DELETE_MODAL_KEEP: 'Keep Campaign',
  DELETE_MODAL_DELETE: 'Delete Campaign',

  // Edit Modal
  EDIT_MODAL_TITLE: 'Edit Campaign Details',
  EDIT_MODAL_SUBTITLE: 'Manage all fields for',
  EDIT_MODAL_FINANCIALS: 'Financials & Performance',
  EDIT_MODAL_ACTUAL_SPEND: 'Actual Spend',
  EDIT_MODAL_SAVING: 'Updating...',
  EDIT_MODAL_SAVE: 'Save All Changes',

  COMMON_UNASSIGNED: 'Unassigned',
  COMMON_UNASSIGNED_INITIALS: 'UN',
  PAGE_ROLE_ADS_MANAGER: 'Ads Manager',
  PAGE_ROLE_CLIENT: 'Client',

  // Log Performance Modal
  LOG_PERFORMANCE_TITLE: 'Log Daily Performance',
  LOG_PERFORMANCE_SUBTITLE: 'Add new metrics for',
  LOG_PERFORMANCE_LABEL_ADD_SPEND: 'Add to Spend',
  LOG_PERFORMANCE_LABEL_ADD_LEADS: 'Add to Leads',
  LOG_PERFORMANCE_LABEL_ROAS_OPTIONAL: 'New Overall ROAS (Optional)',
  LOG_PERFORMANCE_HISTORY_TITLE: 'Update History',
  LOG_PERFORMANCE_SAVING: 'Saving...',
  LOG_PERFORMANCE_ADD_BTN: 'Add Metrics',
  LOG_PERFORMANCE_DELETE_LOG: 'Delete log',

  // Client Campaigns Page
  CLIENT_CAMPAIGNS_TITLE: 'Your Campaigns',
  CLIENT_CAMPAIGNS_SUBTITLE: 'Track your workflow progress and ad performance',
  CLIENT_CAMPAIGNS_ACTIVE_SINGLE: 'Active Campaign',
  CLIENT_CAMPAIGNS_ACTIVE_PLURAL: 'Active Campaigns',
  CLIENT_CAMPAIGNS_NO_CAMPAIGNS: 'No active campaigns found',
  CLIENT_CAMPAIGNS_WORKFLOW_TITLE: 'Production Workflow',
  CLIENT_CAMPAIGNS_PERFORMANCE_TITLE: 'Live Performance',
  CLIENT_CAMPAIGNS_METRIC_SPENT: 'Spent',
  CLIENT_CAMPAIGNS_METRIC_LEADS: 'Leads',
  CLIENT_CAMPAIGNS_METRIC_ROAS: 'Avg ROAS',
  CLIENT_CAMPAIGNS_ONGOING: '(Ongoing)',

  // Priorities
  PRIORITY_LOW: 'Low',
  PRIORITY_MEDIUM: 'Medium',
  PRIORITY_HIGH: 'High — Urgent',

  // Defaults & Symbols
  CURRENCY_SYMBOL: '₹',
  BUDGET_PER_DAY: '/day',
  DEFAULT_PLATFORM: 'Meta',
  MULTI_PLATFORM: 'Multi',

  // Dashboard
  DASHBOARD_OVERVIEW_TITLE: 'Overview',
  DASHBOARD_LIVE_DATA: 'Live data',
  DASHBOARD_LAST_UPDATED: 'Last updated at',
  DASHBOARD_REFRESH: 'Refresh',
  DASHBOARD_EXPORT: 'Export',
  DASHBOARD_NEW_CAMPAIGN: 'New Campaign',
  DASHBOARD_ARIA_DATE_RANGE: 'Select date range',
  CREATE_CAMPAIGN_PLACEHOLDER_NAME: 'Enter your campaign name',
  CREATE_CAMPAIGN_PLACEHOLDER_BUDGET: 'Enter daily budget',
  CREATE_CAMPAIGN_PLACEHOLDER_LOCATION: 'Enter target locations',
  CREATE_CAMPAIGN_PLACEHOLDER_AUDIENCE: 'Enter target audience details',
  CREATE_CAMPAIGN_PLACEHOLDER_MEDIA_LOCATION: 'Enter drive link or storage path',
  CREATE_CAMPAIGN_PLACEHOLDER_NOTE: 'Enter additional campaign instructions',
  DASHBOARD_ROUTE_CAMPAIGN_MGMT: '/campaign-management',
  DASHBOARD_DEFAULT_DATE_RANGE: '30d',
  DASHBOARD_INDICATOR_STEADY: 'Steady',
  DASHBOARD_INDICATOR_NO_CHANGE: 'No change',
  DASHBOARD_METRIC_TOTAL_CLIENTS: 'Total Clients',
  DASHBOARD_METRIC_ACTIVE_WORKSPACE: 'Active in workspace',
  DASHBOARD_METRIC_SALES: 'Sales',
  DASHBOARD_METRIC_VS_PREV: 'vs last month',
  DASHBOARD_METRIC_COLLECTION: 'Collection',
  DASHBOARD_METRIC_PENDING: 'Pending',
  DASHBOARD_METRIC_NO_OVERDUE: 'No invoices overdue',
  DASHBOARD_METRIC_TODAY_REELS: "Today's Reels",
  DASHBOARD_METRIC_SCHEDULED_TODAY: 'Scheduled for today',
  DASHBOARD_METRIC_AWAITING_RAW: 'Awaiting raw files',
  DASHBOARD_METRIC_PROCESSING: 'Processing',
  DASHBOARD_METRIC_EDITING_QUEUE: 'In editing queue',
  DASHBOARD_METRIC_AD_SPEND_MTD: 'Ad Spend MTD',
  DASHBOARD_METRIC_TARGET_ROAS: 'Target: 3.5×',
  DASHBOARD_METRIC_LAUNCHING_SOON: 'launching soon',
  DASHBOARD_METRIC_TASKS_AT_RISK: 'Tasks At Risk',
  DASHBOARD_METRIC_NEAR_DEADLINE: 'Within 24h deadline',
  DASHBOARD_METRIC_OVERDUE_TASKS: 'Overdue Tasks',
  DASHBOARD_METRIC_ESCALATED: 'escalated',
  DASHBOARD_METRIC_CLIENT_SUMMARY: 'Client Summary',
  DASHBOARD_METRIC_REVENUE: 'Revenue',
  DASHBOARD_METRIC_REELS: 'Reels',
  DASHBOARD_METRIC_META_ADS: 'Meta Ads',
  DASHBOARD_METRIC_TODO: 'To-Do',
  DASHBOARD_CHART_LEGEND_SHOOTING: 'Shooting',
  DASHBOARD_CHART_LEGEND_EDITING: 'Editing',
  DASHBOARD_CHART_LEGEND_ADS_SETUP: 'Ads Setup',
  DASHBOARD_CHART_LEGEND_GOOGLE: 'Google Ads',
  DASHBOARD_METRIC_EFFICIENCY: 'efficiency',
  DASHBOARD_METRIC_NEEDS_ATTENTION: 'Needs attention',
  DASHBOARD_METRIC_ESCALATION_RISK: 'Escalation risk',
  DASHBOARD_CHART_LEADS_TITLE: 'Leads Generated',
  DASHBOARD_CHART_LEADS_SUBTITLE: 'Weekly performance across Meta & Google Ads',
  DASHBOARD_CHART_TASK_TITLE: 'Task Completion by Stage',
  DASHBOARD_CHART_TASK_SUBTITLE: 'Weekly tasks completed per workflow role',
  DASHBOARD_TOP_CAMPAIGNS_TITLE: 'Top Campaigns',
  DASHBOARD_TOP_CAMPAIGNS_SUBTITLE: 'Ranked by ROAS',
  DASHBOARD_ACTIVITY_TITLE: 'Recent Activity',
  DASHBOARD_ACTIVITY_SUBTITLE: 'Live workflow events',
  DASHBOARD_ACTIVITY_TASK_OVERDUE: 'Editing task overdue for',
  DASHBOARD_ACTIVITY_DEADLINE_IN: 'Deadline in',
  DASHBOARD_ACTIVITY_LAUNCHED: 'launched Meta ads campaign',
  DASHBOARD_ACTIVITY_COMPLETED_EDITING: 'completed editing for',
  DASHBOARD_ACTIVITY_UPLOADED_CLIPS: 'uploaded raw clips for',
  DASHBOARD_ACTIVITY_AUTO_ASSIGNED: 'auto-assigned editing task for',
  DASHBOARD_ACTIVITY_COMPLETED_SHOOTING: 'completed shooting for',
  DASHBOARD_ACTIVITY_SUBMITTED_FINAL: 'submitted final edit for',
  DASHBOARD_STAGE_ADS_LIVE: 'Ads Live',
  DASHBOARD_STAGE_REVIEW: 'Review',
  DASHBOARD_STAGE_EDITING: 'Editing',
  DASHBOARD_STAGE_SHOOTING: 'Shooting',
  DASHBOARD_STAGE_RAW_UPLOAD: 'Raw Upload',
  DASHBOARD_STAGE_ADS: 'Ads',
  DASHBOARD_STAGE_COMPLETE: 'Complete',
  DASHBOARD_MONTH_YEAR: 'April 2026',
  EDITOR_DASHBOARD_TITLE: 'Editor Dashboard',
  SHOOTER_DASHBOARD_TITLE: 'Shooter Dashboard',
  MANAGER_DASHBOARD_TITLE: 'Manager Dashboard',
  DASHBOARD_ASSIGNED_TASKS: 'Assigned Tasks',
  DASHBOARD_TASKS_FOUND: 'tasks found in',
  DASHBOARD_WORKFLOW_OVERVIEW: 'Workflow Stage Overview',
  DASHBOARD_TEAM_NOTES: 'Team Notes',
  DASHBOARD_PASSED_TO: 'Passed to',
  DASHBOARD_TASK_FINALIZED: 'Task Finalized',
  DASHBOARD_DAYS_LEFT: 'd left',
  DASHBOARD_TODAY: 'Today',
  DASHBOARD_OVERDUE_LABEL: 'Overdue · ',
  DASHBOARD_FROM: 'From:',

  // Client Management
  CLIENT_MGMT_TITLE: 'Client Management',
  NOTIFICATIONS_TITLE: 'Notifications',
  NOTIFICATIONS_MARK_ALL_READ: 'Mark all read',
  NOTIFICATIONS_CLEAR_ALL: 'Clear all',
  NOTIFICATIONS_UNREAD: 'Unread',
  NOTIFICATIONS_ALL: 'All',
  NOTIFICATIONS_NO_UNREAD: 'No unread notifications',
  NOTIFICATIONS_NO_NOTIFS: 'No notifications yet',
  NOTIFICATIONS_BY: 'By',
  NOTIFICATIONS_AGO_MINS: 'm ago',
  NOTIFICATIONS_AGO_HRS: 'h ago',
  NOTIFICATIONS_AGO_DAYS: 'd ago',
  NOTIFICATIONS_TOTAL: 'total',
  NOTIFICATIONS_MARK_AS_READ: 'Mark as read',
  NOTIFICATIONS_DELETE: 'Delete',

  DASHBOARD_TOTAL_TASKS: 'Total Tasks',
  DASHBOARD_OVERDUE: 'Overdue',
  DASHBOARD_TEAM_OVERVIEW: 'Team Overview',
  DASHBOARD_ALL_TASKS: 'All Tasks',
  DASHBOARD_ALL: 'All',
  DASHBOARD_DONE: 'done',

  REPORTS_TITLE: 'Reports',
  REPORTS_SUBTITLE: 'Campaign performance overview across all clients',
  REPORTS_EXPORT: 'Export',
  REPORTS_TOTAL_BUDGET: 'Total Budget',
  REPORTS_TOTAL_SPENT: 'Total Spent',
  REPORTS_TOTAL_LEADS: 'Total Leads',
  REPORTS_AVG_ROAS: 'Avg ROAS',
  REPORTS_MONTHLY_CHART: 'Monthly Spend & Leads',
  REPORTS_STAGE_CHART: 'Campaign Stages',
  REPORTS_PERFORMANCE_TABLE: 'Campaign Performance',
  REPORTS_DATE_RANGE_7: 'Last 7 days',
  REPORTS_DATE_RANGE_30: 'Last 30 days',
  REPORTS_DATE_RANGE_90: 'Last 90 days',
  REPORTS_DATE_RANGE_ALL: 'All time',

  ADS_TABLE_COL_BUDGET: 'Budget',

  SETTINGS_TITLE: 'Settings',
  SETTINGS_SUBTITLE: 'Manage your account preferences and configuration',
  SETTINGS_TAB_PROFILE: 'Profile',
  SETTINGS_TAB_NOTIFICATIONS: 'Notifications',
  SETTINGS_TAB_SECURITY: 'Security',
  SETTINGS_TAB_APPEARANCE: 'Appearance',
  SETTINGS_PROFILE_INFO: 'Profile Information',
  SETTINGS_PROFILE_SUBTITLE: 'Update your name, email, and bio',
  SETTINGS_CHANGE_PHOTO: 'Change Photo',
  SETTINGS_FULL_NAME: 'Full Name',
  SETTINGS_EMAIL_ADDR: 'Email Address',
  SETTINGS_BIO: 'Bio',
  SETTINGS_SAVE_CHANGES: 'Save Changes',
  SETTINGS_NOTIF_PREFS: 'Notification Preferences',
  SETTINGS_NOTIF_SUBTITLE: 'Manage events that trigger system notifications',
  SETTINGS_UPDATE_PREFS: 'Update Preferences',
  SETTINGS_ACCOUNT_SECURITY: 'Account Security',
  SETTINGS_SECURITY_SUBTITLE: 'Manage authentication credentials',
  SETTINGS_CURRENT_PWD: 'Current Password',
  SETTINGS_NEW_PWD: 'New Password',
  SETTINGS_CONFIRM_PWD: 'Confirm Password',
  SETTINGS_UPDATE_PWD: 'Update Password',
  SETTINGS_ACCENT_COLOR: 'Accent Color',
  SETTINGS_SIDEBAR_STYLE: 'Sidebar Style',
  SETTINGS_NOTIF_TASK_ASSIGNED: 'Task Assigned',
  SETTINGS_NOTIF_TASK_ASSIGNED_DESC: 'When a new task is assigned to you',
  SETTINGS_NOTIF_TASK_COMPLETED: 'Task Completed',
  SETTINGS_NOTIF_TASK_COMPLETED_DESC: 'When a task you created is completed',
  SETTINGS_NOTIF_DEADLINE: 'Deadline Reminders',
  SETTINGS_NOTIF_DEADLINE_DESC: '24h before a task deadline',
  SETTINGS_NOTIF_CAMPAIGN: 'Campaign Updates',
  SETTINGS_NOTIF_CAMPAIGN_DESC: 'Status changes on active campaigns',
  SETTINGS_NOTIF_HANDOFF: 'Workflow Handoffs',
  SETTINGS_NOTIF_HANDOFF_DESC: 'When content is passed to the next role',
  COLOR_VIOLET: 'Violet',
  COLOR_BLUE: 'Blue',
  COLOR_TEAL: 'Teal',
  COLOR_ROSE: 'Rose',
  COLOR_AMBER: 'Amber',
  SETTINGS_BIO_DEFAULT: 'Marketing agency professional focused on delivering results.',
  SETTINGS_ACTIVE_ACCOUNT: 'Active Account',
  SETTINGS_PHOTO_REQUIREMENTS: 'JPG, PNG up to 2MB',
  SETTINGS_ROLE_LABEL: 'Role:',
  SETTINGS_ROLE_AUTH_NOTICE: 'Role modifications require administrative authorization',
  SETTINGS_CURRENT_PWD_PLACEHOLDER: 'Enter current password',
  SETTINGS_NEW_PWD_PLACEHOLDER: 'Minimum 8 characters',
  SETTINGS_CONFIRM_PWD_PLACEHOLDER: 'Repeat new password',
  SETTINGS_SECURITY_NOTICE:
    'Note: Password management is currently in evaluation mode. Integration with secure auth providers is required for production persistence.',
  SETTINGS_APPEARANCE_SUBTITLE: 'Personalize your workspace visual theme',
  SIDEBAR_COMPACT: 'Compact',
  SIDEBAR_EXPANDED: 'Expanded',
  SETTINGS_APPEARANCE_NOTICE: 'Custom color profiles will be available in the Enterprise edition.',
  CLIENT_MGMT_ADD_CLIENT: 'Add Client',
  CLIENT_MGMT_SEARCH_PLACEHOLDER: 'Search by name or brand…',
  CLIENT_MGMT_NO_CLIENTS: 'No clients found',
  SETTINGS_ERR_NAME_REQ: 'Name is required',
  SETTINGS_TOAST_PROFILE_UPDATED: 'Profile updated successfully',
  SETTINGS_ERR_CURRENT_PWD_REQ: 'Enter your current password',
  SETTINGS_ERR_PWD_MIN: 'New password must be at least 8 characters',
  SETTINGS_ERR_PWD_MISMATCH: 'Passwords do not match',
  SETTINGS_TOAST_PWD_CHANGED: 'Password changed successfully',
  SETTINGS_TOAST_NOTIF_UPDATED: 'Notification preferences updated',
  SETTINGS_TOAST_ACCENT_APPLIED: 'accent applied',
  SETTINGS_TOAST_SIDEBAR_COMING: 'mode coming in next update',
  CLIENT_MGMT_RECORD_PAYMENT: 'Record Client Payment',
  CLIENT_MGMT_RECORD_PAYMENT_SUBTITLE: 'Log a new payment received from this client',
  CLIENT_MGMT_RECORD_PAYMENT_BTN: 'Record Payment',
  CLIENT_MGMT_PAYMENT_HISTORY: 'Payment History',
  CLIENT_MGMT_PAYMENT_HISTORY_SUBTITLE: 'Payments received from',
  CLIENT_MGMT_TOTAL_PAID: 'Total Paid',
  CLIENT_MGMT_PENDING_BALANCE: 'Pending Balance',
  CLIENT_MGMT_NO_PAYMENTS: 'No payment records found for this client.',
  CLIENT_MGMT_ERR_VALID_AMOUNT: 'Please enter a valid amount',
  CAMPAIGN_MGMT_VIEW_ALL: 'View All',
  CAMPAIGN_MGMT_TABLE_COL_NAME: 'Campaign',

  CLIENT_MGMT_ERR_PAYMENT_EXCEEDS: 'Payment exceeds package limit',
  CLIENT_MGMT_LABEL_CLIENT_NAME: 'Client Name',
  CLIENT_MGMT_LABEL_BRAND_NAME: 'Brand Name',
  CLIENT_MGMT_LABEL_SERVICES: 'Services Required',
  CLIENT_MGMT_LABEL_PACKAGE: 'Package (INR)',
  CLIENT_MGMT_LABEL_PER_DAY_SPEND: 'Per Day Spend Amount',
  CLIENT_MGMT_LABEL_PLAN_TYPE: 'Plan Type',
  CLIENT_MGMT_LABEL_AD_RUN: 'Which AD Run',
  CLIENT_MGMT_LABEL_REELS_PER_MONTH: 'Reels Per Month',
  CLIENT_MGMT_LABEL_PLATFORM_TYPE: 'Platform Type',
  CLIENT_MGMT_LABEL_WEBSITE_LINK: 'Website Link',
  CLIENT_MGMT_LABEL_LOCATION: 'Location',
  CLIENT_MGMT_PLACEHOLDER_NAME: 'Enter client full name',
  CLIENT_MGMT_PLACEHOLDER_BRAND: 'Enter brand or business name',
  CLIENT_MGMT_PLACEHOLDER_PACKAGE: 'Enter package amount',
  CLIENT_MGMT_PLACEHOLDER_SPEND: 'Enter per day spend',
  CLIENT_MGMT_PLACEHOLDER_AD_RUN: 'Enter ad types to run',
  CLIENT_MGMT_PLACEHOLDER_REELS: 'Enter number of reels',
  CLIENT_MGMT_PLACEHOLDER_WEBSITE: 'Enter website URL',
  CLIENT_MGMT_PLACEHOLDER_LOCATION: 'Enter business location',
  CLIENT_MGMT_EDIT_CLIENT: 'Edit Client',
  CLIENT_MGMT_DELETE_CLIENT: 'Delete Client',
  CLIENT_MGMT_DELETE_CONFIRM: 'Are you sure you want to delete',
  CLIENT_MGMT_DELETE_DESC: 'All associated data will be permanently removed.',
  ADS_TABLE_COL_ACTIONS: 'Actions',
  CAMPAIGN_MGMT_CANCEL: 'Cancel',
  CAMPAIGN_MGMT_SAVE_CHANGES: 'Save Changes',
  CAMPAIGN_MGMT_NOTES: 'Notes',

  // Client Portal
  CLIENT_PROFILE_TITLE: 'Client Profile',
  CLIENT_PROFILE_ACTIVE: 'Active',
  CLIENT_PROFILE_CURRENT_PLAN: 'Current Plan',
  CLIENT_PROFILE_FINANCIALS: 'Contract & Financials',
  CLIENT_PROFILE_TOTAL_PACKAGE: 'Total Package',
  CLIENT_PROFILE_DAILY_SPEND: 'Daily Ad Spend',
  CLIENT_PROFILE_STRATEGY: 'Campaign Strategy',
  CLIENT_PROFILE_AD_TYPE: 'Primary Ad Type',
  CLIENT_PROFILE_CONTENT_QUOTA: 'Content Quota',
  CLIENT_PROFILE_TARGET_PLATFORM: 'Target Platform',
  CLIENT_PROFILE_PRIMARY_CHANNEL: 'Primary Channel',
  CLIENT_PROFILE_WEBSITE: 'Website URL',
  CLIENT_PROFILE_ACTIVE_SERVICES: 'Active Services',

  CLIENT_REELS_TITLE: 'Reels Schedule',
  CLIENT_REELS_SUBTITLE: 'Production pipeline & upload calendar',
  CLIENT_REELS_ALL: 'All Reels',
  CLIENT_REELS_NO_REELS: 'No reels found matching your selection.',
  CLIENT_REELS_SCHEDULED: 'Scheduled',
  CLIENT_REELS_PRODUCTION: 'Production',
  CLIENT_REELS_UPLOADED: 'Uploaded',
  CLIENT_REELS_GENERAL_CONTENT: 'General Content',
  CLIENT_PROFILE_PLAN_SUFFIX: 'Plan',
  CLIENT_PROFILE_REELS_SUFFIX: 'Reels / Month',
  LOGIN_AUTH_AUTOFILLED: 'Autofilled',
  LOGIN_AUTH_CREDENTIALS: 'credentials',

  LOGIN_PLATFORM_NAME: 'AgencyFlow',
  LOGIN_SUBTITLE_PLATFORM: 'Campaign Automation Platform',
  LOGIN_HERO_TITLE_PART1: 'Your entire agency',
  LOGIN_HERO_TITLE_PART2: 'on autopilot.',
  LOGIN_HERO_DESC: 'From shoot to ad launch — AgencyFlow routes every task automatically so your team ships faster and your clients see results.',
  LOGIN_FEATURE_PIPELINE: 'Auto-route tasks through your entire production pipeline',
  LOGIN_FEATURE_ADS: 'Track ad spend, ROAS, and leads across Meta & Google',
  LOGIN_FEATURE_SCALE: 'Manage 50+ clients and 200+ active tasks simultaneously',
  LOGIN_FEATURE_ROLES: 'Role-based access for every team member',
  LOGIN_STAT_CLIENTS: 'Active Clients',
  LOGIN_STAT_TASKS: 'Tasks Managed',
  LOGIN_STAT_ROAS: 'Avg ROAS',
  LOGIN_FORM_EMAIL_LABEL: 'Work Email',
  LOGIN_FORM_EMAIL_PLACEHOLDER: 'you@agency.io',
  LOGIN_FORM_PWD_LABEL: 'Password',
  LOGIN_FORM_PWD_FORGOT: 'Forgot password?',
  LOGIN_FORM_PWD_PLACEHOLDER: '••••••••',
  LOGIN_FORM_REMEMBER: 'Keep me signed in for 30 days',
  LOGIN_FORM_SIGNING_IN: 'Signing in…',
  LOGIN_FORM_SIGN_IN_BTN: 'Sign In',
  LOGIN_DEMO_ROLE: 'Role',
  LOGIN_DEMO_EMAIL: 'Email',
  LOGIN_DEMO_USE: 'Use',
  LOGIN_DEMO_PWD_NOTICE: 'All demo accounts share the same password format:',
  LOGIN_NO_ACCOUNT: "Don't have an account?",
  LOGIN_REQUEST_ACCESS: 'Request access',
  LOGIN_TERMS_AGREEMENT: 'By signing in, you agree to our',
  LOGIN_TERMS_SERVICE: 'Terms of Service',
  LOGIN_AND: 'and',
  LOGIN_PRIVACY_POLICY: 'Privacy Policy',
  LOGIN_ERR_EMAIL_REQ: 'Email is required',
  LOGIN_ERR_EMAIL_INVALID: 'Enter a valid email address',
  LOGIN_ERR_PWD_REQ: 'Password is required',
  LOGIN_ERR_PWD_MIN: 'Password must be at least 6 characters',
  SMM_DASHBOARD_TITLE: 'Reels Schedule',
  SMM_DASHBOARD_DESC: 'Manage and track scheduled reel uploads for your campaigns',
  SMM_ADD_REEL: 'Add New Reel',
  SMM_STAT_UPCOMING: 'Upcoming',
  SMM_STAT_PRODUCTION: 'In Production',
  SMM_STAT_UPLOADED: 'Uploaded',
  SMM_SEARCH_PLACEHOLDER: 'Search reels by title or client...',
  SMM_TAB_ALL: 'All Reels',
  SMM_TAB_SCHEDULED: 'Scheduled',
  SMM_TAB_PRODUCTION: 'Production',
  SMM_TAB_UPLOADED: 'Uploaded',
  SMM_MODAL_TITLE: 'Schedule New Reel',
  SMM_LABEL_TITLE: 'Reel Title',
  SMM_PLACEHOLDER_TITLE: 'e.g., Spring Collection Promo #1',
  SMM_LABEL_CLIENT: 'Client',
  SMM_PLACEHOLDER_CLIENT: 'Select client...',
  SMM_LABEL_DATE: 'Schedule Date',
  SMM_BTN_CANCEL: 'Cancel',
  SMM_BTN_SCHEDULE: 'Schedule Reel',
  SMM_TOAST_UPLOADED: 'Reel marked as uploaded!',
  SMM_TOAST_ADDED: 'New reel added to schedule',
  SMM_TOAST_ERROR: 'Failed to add reel',
  SMM_NO_REELS: 'No reels found',
  SMM_NO_REELS_DESC: 'Try adjusting your filters or search query.',
  SMM_LABEL_REEL: 'Reel',
  SMM_LABEL_REELS: 'Reels',
  SMM_PRIVATE_CLIENT: 'Private Client',
  SMM_OVERDUE: 'Overdue',
  COMMON_OPTIONAL: 'Optional',
  COMMON_REMOVE: 'Remove',
  TASK_MGMT_TITLE: 'Task Management',
  TASK_MGMT_TASKS_SUBTITLE: 'tasks across all roles',
  TASK_MGMT_ADD_TASK: 'Add Task',
  TASK_MGMT_TOTAL_TASKS: 'Total Tasks',
  TASK_MGMT_IN_PROGRESS: 'In Progress',
  TASK_MGMT_COMPLETED: 'Completed',
  TASK_MGMT_OVERDUE: 'Overdue',
  TASK_MGMT_ALL_STATUSES: 'All Statuses',
  TASK_MGMT_PENDING: 'Pending',
  TASK_MGMT_SEARCH_PLACEHOLDER: 'Search tasks…',
  TASK_MGMT_COL_TASK: 'Task',
  TASK_MGMT_COL_ASSIGNED_TO: 'Assigned To',
  TASK_MGMT_COL_ROLE: 'Role',
  TASK_MGMT_COL_CLIENT: 'Client',
  TASK_MGMT_COL_DEADLINE: 'Deadline',
  TASK_MGMT_COL_STATUS: 'Status',
  TASK_MGMT_COL_ACTIONS: 'Actions',
  TASK_MGMT_NO_TASKS: 'No tasks found',
  TASK_MGMT_EDIT_TASK: 'Edit Task',
  TASK_MGMT_ADD_NEW_TASK: 'Add New Task',
  TASK_MGMT_PLACEHOLDER_TITLE: 'Enter task title',
  TASK_MGMT_PLACEHOLDER_DESC: 'Enter detailed task description',
  TASK_MGMT_LABEL_TITLE: 'Task Title',
  TASK_MGMT_SELECT_TEAMMATE: 'Select teammate…',
  TASK_MGMT_SELECT_CLIENT: 'Select client…',
  TASK_MGMT_CONFIRM_DELETE: 'Confirm Deletion',
  TASK_MGMT_DELETE_PROMPT: 'Are you sure you want to permanently delete the task',
  TASK_MGMT_BTN_DELETE: 'Delete',
  TASK_MGMT_PAGINATION_SHOW: 'Show',
  TASK_MGMT_PAGINATION_OF: 'of',
  TASK_MGMT_PAGINATION_ENTRIES: 'entries',

  TEAM_PAGE_TITLE: 'Team',
  TEAM_PAGE_SUBTITLE_PART1: 'active',
  TEAM_PAGE_SUBTITLE_PART2: 'total members',
  TEAM_PAGE_INVITE_MEMBER: 'Invite Member',
  TEAM_PAGE_SEARCH_PLACEHOLDER: 'Search by name or email…',
  TEAM_PAGE_COL_MEMBER: 'Member',
  TEAM_PAGE_COL_JOINED: 'Joined',
  TEAM_PAGE_STATUS_ACTIVE: 'Active',
  TEAM_PAGE_STATUS_INACTIVE: 'Inactive',
  TEAM_PAGE_EDIT_MEMBER_TOOLTIP: 'Edit member',
  TEAM_PAGE_REMOVE_MEMBER_TOOLTIP: 'Remove member',
  TEAM_PAGE_MODAL_EDIT_TITLE: 'Edit Member',
  TEAM_PAGE_MODAL_INVITE_TITLE: 'Invite Team Member',
  TEAM_PAGE_MODAL_EDIT_SUBTITLE: 'Update member details',
  TEAM_PAGE_MODAL_INVITE_SUBTITLE: 'Add a new member to your agency team',
  TEAM_PAGE_LABEL_FULL_NAME: 'Full Name',
  TEAM_PAGE_LABEL_EMAIL: 'Email Address',
  TEAM_PAGE_BTN_SEND_INVITE: 'Send Invite',
  TEAM_PAGE_CONFIRM_REMOVE_TITLE: 'Remove Member?',
  TEAM_PAGE_CONFIRM_REMOVE_SUBTITLE: 'This will remove the member from your team.',
  TEAM_PAGE_BTN_REMOVE: 'Remove',
  NOT_FOUND_TITLE: 'Page Not Found',
  NOT_FOUND_DESC: "The page you're looking for doesn't exist. Let's get you back!",
  NOT_FOUND_GO_BACK: 'Go Back',
  NOT_FOUND_BACK_HOME: 'Back to Home',
  TASK_MODAL_CONFIRM_REEL: 'Confirm Reel Upload',
  TASK_MODAL_COMPLETE_TASK: 'Complete Task',
  TASK_MODAL_LABEL_NOTES: 'Completion/Handoff Notes',
  TASK_MODAL_PLACEHOLDER_NOTES: 'Provide details for the next person or audit records...',
  TASK_MODAL_ERR_NOTES: 'Descriptive notes are required (min 5 chars)',
  TASK_MODAL_ERR_HANDOFF: 'Please select a team member to hand off to',
  TASK_MODAL_ERR_SCREENSHOT: 'Campaign delivery screenshot is required',
  TASK_MODAL_LABEL_DELIVERY_SS: 'Delivery Screenshot',
  TASK_MODAL_LABEL_EXPORT_SS: 'Export/Preview Screenshot',
  TASK_MODAL_SS_ATTACHED: 'Screenshot Attached',
  TASK_MODAL_UPLOAD_PROOF: 'Click to upload campaign proof',
  TASK_MODAL_UPLOAD_PREVIEW: 'Click to upload edit preview/confirmation',
  TASK_MODAL_LABEL_HANDOFF: 'Hand Off To',
  TASK_MODAL_SELECT_RECIPIENT: 'Select recipient…',
  TASK_MODAL_BTN_COMPLETE_HANDOFF: 'Complete & Hand Off',
  TASK_MODAL_BTN_CONFIRM_UPLOAD: 'Confirm Upload',

  // Super Admin Business Agency
  BA_PAGE_TITLE: 'Business Agencies',
  BA_PAGE_DESC: 'Platform-wide agency governance and subscription management.',
  BA_ADD_NEW: 'Add New Agency',
  BA_SEARCH_PLACEHOLDER: 'Search by name, owner, email or mobile...',
  BA_COL_OWNER: 'Owner & Contact',
  BA_COL_AGENCY: 'Agency',
  BA_COL_STATUS: 'Status',
  BA_COL_SUBSCRIPTION: 'Subscription',
  BA_COL_LAST_ACTIVE: 'Last Active',
  BA_COL_ACTIONS: 'Actions',
  BA_LOADING: 'Loading agencies...',
  BA_NO_AGENCIES: 'No agencies match your search criteria',
  BA_SUB_FREE: 'Free Trial',
  BA_SUB_PREMIUM: 'Premium',
  BA_EDIT_TITLE: 'Edit Agency',
  BA_EDIT_DESC: 'Configure agency profile and subscription details.',
  BA_LABEL_NAME: 'Agency Name',
  BA_LABEL_OWNER: 'Owner Name',
  BA_LABEL_EMAIL: 'Email Address',
  BA_LABEL_MOBILE: 'Mobile Number',
  BA_PLACEHOLDER_NAME: 'Enter Agency Name',
  BA_PLACEHOLDER_OWNER: 'Enter Owner Name',
  BA_PLACEHOLDER_EMAIL: 'Enter Email Address',
  BA_PLACEHOLDER_MOBILE: 'Enter Mobile Number',
  BA_CREATE_BTN: 'Create Agency',
  BA_CONFIRM_DELETE: 'Are you sure you want to delete this agency?',
  BA_TOAST_UPDATING: 'Updating agency...',
  BA_TOAST_ADDING: 'Adding agency...',
  BA_TOAST_UPDATED: 'Agency updated successfully',
  BA_TOAST_ADDED: 'Agency added successfully',
  BA_TOAST_DELETING: 'Deleting agency...',
  BA_TOAST_DELETED: 'Agency deleted successfully',
  BA_TOAST_STATUS_PREFIX: 'Agency marked as',
  BA_DETAIL_VIEWS: 'Views',
  BA_DETAIL_ACTIONS: 'Actions',
  BA_DETAIL_BEST: 'Best',
  BA_DETAIL_LOW: 'Low',
  BA_DETAIL_VIEWS_DESC: 'Total Module Views',
  BA_DETAIL_ACTIONS_DESC: 'Total Data Actions',
  BA_DETAIL_TOP_MODULE: 'Top Module',
  BA_DETAIL_LOW_MODULE: 'Low Module',
  BA_DETAIL_SNAPSHOT: 'Business Snapshot',
  BA_DETAIL_OWNER_DETAIL: 'Owner Detail',
  BA_DETAIL_TIMELINE: 'Plan Timeline',
  BA_DETAIL_STARTED: 'Started:',
  BA_DETAIL_EXPIRES: 'Expires:',
  BA_DETAIL_DAYS_LEFT: 'Days Left',
  BA_DETAIL_ROLE_ACTIVITY: 'Role-Wise Activity',
  BA_DETAIL_COL_MODULE: 'Module Name',
  BA_DETAIL_COL_ENTERED: 'Entered',
  BA_DETAIL_COL_SCORE: 'Score',

  // Super Admin Dashboard
  SA_DASHBOARD_TITLE: 'Dashboard',
  SA_DASHBOARD_DESC: 'Real-time governance and module performance analytics.',
  SA_METRIC_TOTAL_AGENCY: 'Total Agency',
  SA_METRIC_ACTIVE_AGENCIES: 'Active Agencies',
  SA_METRIC_TOTAL_VIEWS: 'Total Module Views',
  SA_METRIC_TOTAL_ACTIONS: 'Total Data Actions',
  SA_DASHBOARD_LOADING: 'Loading system metrics...',
  SA_HIGHLIGHTS_TITLE: 'Feature uses highlights',
  SA_HIGHLIGHTS_EXTREME: 'Daily Extreme',
  SA_HIGHLIGHTS_HIGHEST: 'HIGHEST USAGE',
  SA_HIGHLIGHTS_LOWEST: 'LOWEST USAGE',
  SA_HIGHLIGHTS_AVG_VIEWS: 'Avg Views',
  SA_HIGHLIGHTS_EFFICIENCY: 'Efficiency',
  SA_HIGHLIGHTS_ACTION_REQ: 'Action Req.',
  SA_ACTIVITY_TITLE: 'Recent Activity',
  SA_ACTIVITY_DESC: 'Platform governance feed',
  SA_ACTIVITY_LIVE: 'Live Feed',
  SA_BREAKDOWN_TITLE: 'Module Usage Breakdown',
  SA_BREAKDOWN_PANEL: 'Panel Analytics',
  SA_BREAKDOWN_COUNT_SUFFIX: 'Active Modules',
  SA_BREAKDOWN_EMPTY: 'No active modules found for this role.',
  SA_BREAKDOWN_COL_VIEWS: 'Views/Clicks',
  SA_BREAKDOWN_COL_UNIQUE: 'Unique Base',

  // Super Admin Subscription
  SUB_PAGE_TITLE: 'Subscription',
  SUB_PAGE_DESC: 'Monitor and manage agency billing cycles and plan distributions.',
  SUB_STAT_PREMIUM: 'Premium Active',
  SUB_STAT_TRIAL: 'On Trial',
  SUB_STAT_EXPIRING: 'Expiring Soon',
  SUB_STAT_EXPIRED: 'Expired',
  SUB_LOADING: 'Processing subscription data...',
  SUB_BREAKDOWN_TITLE: 'Subscription Breakdown',
  SUB_EXPIRING_TITLE: 'Expired within 5 days',
  SUB_EXPIRING_EMPTY: 'No upcoming expirations.',
  SUB_MANAGE_TITLE: 'Manage Account',
  SUB_COL_EXPIRY: 'Expiry',
  SUB_BTN_END_NOW: 'End Now',
  SUB_TOAST_TERMINATING: 'Terminating subscription...',
  SUB_TOAST_TERMINATED_PREFIX: 'Subscription for',
  SUB_TOAST_TERMINATED_SUFFIX: 'ended.',
  SUB_TOAST_SAVING: 'Saving changes...',
  SUB_TOAST_SAVED_PREFIX: 'Account settings for',
  SUB_TOAST_SAVED_SUFFIX: 'saved.',

  CLIENT_MGMT_NAME_REQUIRED: 'Client name is required',
  CLIENT_MGMT_BRAND_REQUIRED: 'Brand name is required',
  CLIENT_MGMT_PACKAGE_REQUIRED: 'Enter a valid package amount',
  CLIENT_MGMT_ERR_PER_DAY_SPEND: 'Per day spend is required',
  CLIENT_MGMT_ERR_AD_TYPE: 'AD Type is required',
  CLIENT_MGMT_ERR_PLATFORM_TYPE: 'Platform type is required',
  CLIENT_MGMT_ERR_WEBSITE_LINK: 'Website link is required',
  CLIENT_MGMT_ERR_LOCATION: 'Location is required',
  CLIENT_MGMT_ERR_SERVICES: 'At least one service is required',
  CLIENT_MGMT_ERR_REELS_PER_MONTH: 'Reels per month is required',
  CLIENT_MGMT_INVALID_AMOUNT: 'Please enter a valid amount',
  CLIENT_MGMT_SELECT_PLATFORM: 'Select Platform',
  CLIENT_MGMT_PLATFORM_WEBSITE: 'Website',
  CLIENT_MGMT_PLATFORM_OFFLINE: 'Offline',
  CLIENT_MGMT_RECORD_PAYMENT_TOOLTIP: 'Record Payment',
  CLIENT_MGMT_VIEW_PAYMENTS_TOOLTIP: 'View Payments',
  CLIENT_MGMT_EDIT_CLIENT_TOOLTIP: 'Edit client',
  CLIENT_MGMT_DELETE_CLIENT_TOOLTIP: 'Delete client',
  CLIENT_MGMT_PAYMENT_NOTES_PLACEHOLDER: 'Payment method, invoice #, etc.',
  CLIENT_MGMT_CLOSE: 'Close',

  CLIENT_MGMT_TOAST_UPDATED_PREFIX: 'Client "',
  CLIENT_MGMT_TOAST_UPDATED_SUFFIX: '" updated',
  CLIENT_MGMT_TOAST_ADDED_PREFIX: 'Client "',
  CLIENT_MGMT_TOAST_ADDED_SUFFIX: '" added',
  CLIENT_MGMT_TOAST_REMOVED_PREFIX: 'Client "',
  CLIENT_MGMT_TOAST_REMOVED_SUFFIX: '" removed',
  CLIENT_MGMT_TOAST_PAYMENT_PREFIX: 'Payment of ',
  CLIENT_MGMT_TOAST_PAYMENT_MID: ' recorded for ',

  CLIENT_MGMT_MODAL_EDIT_SUBTITLE: 'Update client details below',
  CLIENT_MGMT_MODAL_ADD_SUBTITLE: 'Fill in the details to add a new client',
  CLIENT_MGMT_TOAST_PAYMENT_REMOVED: 'Payment entry removed',

  CLIENT_MGMT_SERVICE_REELS: 'Reels',
  CLIENT_MGMT_SERVICE_CAMPAIGN: 'Campaign',
  CLIENT_MGMT_SERVICE_META: 'Meta',
  CLIENT_MGMT_SERVICE_SOCIAL: 'Social Media',

  CLIENT_MGMT_PLAN_WEEKLY: 'Weekly',
  CLIENT_MGMT_PLAN_MONTHLY: 'Monthly',
  CLIENT_MGMT_PLAN_YEARLY: 'Yearly',
} as const;

export const SUPER_ADMIN_ACTIONS = {
  GET_OWNERS: 'get_owners',
  ADD_OWNER: 'add_owner',
  UPDATE_OWNER: 'update_owner',
  DELETE_OWNER: 'delete_owner',
} as const;

export const AUTH_ACTIONS = {
  LOGIN: 'login',
  REQUEST_OTP: 'request_otp',
  VERIFY_OTP: 'verify_otp',
} as const;

export const PAGE_ROLES = {
  ADS_TRACKING: [
    ROLES.OWNER,
    ROLES.ADS_MANAGER,
    ROLES.SOCIAL_MEDIA_MANAGER,
    ROLES.MANAGER,
  ],
  CAMPAIGN_MANAGEMENT: [
    ROLES.OWNER,
    ROLES.MANAGER,
    ROLES.SOCIAL_MEDIA_MANAGER,
    ROLES.ADS_MANAGER,
  ],
  EDITOR_DASHBOARD: [
    ROLES.OWNER,
    ROLES.MANAGER,
    ROLES.EDITOR,
  ],
  SHOOTER_DASHBOARD: [
    ROLES.OWNER,
    ROLES.MANAGER,
    ROLES.SHOOTER,
  ],
  MANAGER_DASHBOARD: [
    ROLES.OWNER,
    ROLES.MANAGER,
  ],
  SOCIAL_MEDIA_DASHBOARD: [
    ROLES.OWNER,
    ROLES.MANAGER,
    ROLES.SOCIAL_MEDIA_MANAGER,
  ],
  TASK_MANAGEMENT: [
    ROLES.OWNER,
    ROLES.MANAGER,
    ROLES.SHOOTER,
    ROLES.EDITOR,
    ROLES.ADS_MANAGER,
    ROLES.SOCIAL_MEDIA_MANAGER,
  ],
  TEAM: [
    ROLES.OWNER,
    ROLES.MANAGER,
    ROLES.SHOOTER,
    ROLES.EDITOR,
    ROLES.ADS_MANAGER,
    ROLES.SOCIAL_MEDIA_MANAGER,
  ],
  REPORTS: [
    ROLES.OWNER,
    ROLES.MANAGER,
  ],
} as const;
export const STORAGE_KEYS = {
  AUTH_TOKEN: 'auth_token',
  USER_DATA: 'user_data',
  ADS_METRICS: 'agencyflow_ads_metrics',
  CAMPAIGNS: 'agencyflow_campaigns',
} as const;

export const ADS_FILTER_KEYS = {
  ALL: 'all',
  META: 'Meta',
  GOOGLE: 'Google',
  INSTAGRAM: 'Instagram',
  TIKTOK: 'TikTok',
} as const;

export const ADS_DATE_RANGE_KEYS = {
  LAST_7D: '7d',
  LAST_30D: '30d',
  LAST_90D: '90d',
} as const;

export const STORAGE_KEY_CAMPAIGNS = STORAGE_KEYS.CAMPAIGNS;

export const PLATFORM_OPTIONS = ['Meta', 'Facebook', 'Instagram', 'Google', 'TikTok', 'LinkedIn', 'Multi'] as const;

export const CAMPAIGN_STATUS_OPTIONS = [
  STATIC_STRINGS.ADS_STATUS_ACTIVE,
  STATIC_STRINGS.ADS_STATUS_DRAFT,
  STATIC_STRINGS.ADS_STATUS_PAUSED,
  STATIC_STRINGS.ADS_STATUS_COMPLETED,
  STATIC_STRINGS.ADS_STATUS_ARCHIVED,
] as const;

export const CAMPAIGN_STAGE_OPTIONS = ['in draft', 'in review', 'process', 'publish'] as const;

export const ADS_DATE_RANGE_OPTIONS = [
  { label: STATIC_STRINGS.ADS_DATE_RANGE_7D, value: '7d' },
  { label: STATIC_STRINGS.ADS_DATE_RANGE_30D, value: '30d' },
  { label: STATIC_STRINGS.ADS_DATE_RANGE_90D, value: '90d' },
] as const;

export const CLIENT_OPTIONS = [
  'Luma Apparel', 'Nexus Capital', 'Orion Fitness', 'Synapse Tech',
  'Coral Beauty', 'Pulse Nutrition', 'Helios Solar', 'Bloom Skincare',
] as const;

export const TEAM_MEMBERS = [
  { id: 'user-001', name: 'Marco Reyes', role: ROLES.SHOOTER },
  { id: 'user-002', name: 'Jin Park', role: ROLES.EDITOR },
  { id: 'user-003', name: 'Sofia Nguyen', role: ROLES.ADS_MANAGER },
  { id: 'user-004', name: 'Priya Sharma', role: ROLES.MANAGER },
  { id: 'user-005', name: 'Kai Tanaka', role: ROLES.SHOOTER },
  { id: 'user-006', name: 'Amara Diallo', role: ROLES.EDITOR },
] as const;

export const OBJECTIVE_OPTIONS = [
  'Traffic', 'Awareness', 'Sales', 'Engagement', 'Leads', 'App Promotion',
] as const;
